apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tdacbns3b-python
  janus-idp.io/tekton: tdacbns3b-python
  backstage.io/kubernetes-id: tdacbns3b-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tdacbns3b-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
